version: '3'
services:
  web: 
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        - ./client/node_modules
        - ./client:/app/client
      
  