version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    env_file:
      - .env
    volumes:
      - /app/node_modules # "don't try to override it, just leave it as is"
      - ./server:/app # when our application tries to access anything inside the app directory, except for node_modules folder, is going to be redirected to server (allowing updates any time we make changes in our local source)
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app # everything inside the client directory should be shared inside the app container
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
